# Databricks notebook source
# MAGIC %md
# MAGIC # Does More Data Improve Severity Prediction?
# MAGIC ## Home Insurance GBM Severity Comparison
# MAGIC
# MAGIC This notebook trains two **Gradient Boosted Machine (GBM)** severity models and compares
# MAGIC their performance. It mirrors the frequency GLM comparison in notebook 01, but for
# MAGIC **claim cost given that a claim has occurred**.
# MAGIC
# MAGIC | | Model 1 — Standard | Model 2 — Enriched |
# MAGIC |---|---|---|
# MAGIC | **Features** | Classic rating factors | Standard + geo/risk enrichment |
# MAGIC | **Goal** | Baseline severity prediction | Show uplift from new data |
# MAGIC
# MAGIC **All artefacts are persisted to Unity Catalog:**
# MAGIC - Tables → `lr_serverless_aws_us_catalog.pricing_new_data_impact`

# COMMAND ----------

# MAGIC %pip install lightgbm scikit-learn matplotlib

# COMMAND ----------

dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %md
# MAGIC ## 0. Setup

# COMMAND ----------

CATALOG = "lr_serverless_aws_us_catalog"
SCHEMA = "pricing_new_data_impact"

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
spark.sql(f"USE {CATALOG}.{SCHEMA}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Load Portfolio & Filter to Claimants
# MAGIC
# MAGIC Severity models are trained **only on policies that had at least one claim**.
# MAGIC We reuse the portfolio generated by notebook 01.

# COMMAND ----------

import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error
import matplotlib.pyplot as plt

portfolio = spark.table(f"{CATALOG}.{SCHEMA}.portfolio").toPandas()

# One-hot encode categoricals (same approach as notebook 01)
df_encoded = pd.get_dummies(portfolio, columns=["property_type", "construction", "occupancy"], drop_first=True)
bool_cols = df_encoded.select_dtypes(include=["bool", "uint8"]).columns
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)

# Filter to claimants only
claimants = df_encoded[df_encoded["num_claims"] > 0].copy()
print(f"Total policies: {len(df_encoded):,}")
print(f"Claimants:      {len(claimants):,} ({len(claimants)/len(df_encoded):.1%})")
print(f"Avg severity:   £{claimants['claim_severity'].mean():,.0f}")
print(f"Median severity: £{claimants['claim_severity'].median():,.0f}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Train / Test Split & Feature Sets

# COMMAND ----------

standard_features = [
    "building_age", "bedrooms", "sum_insured", "prior_claims", "policy_tenure",
    "property_type_flat", "property_type_semi_detached", "property_type_terraced",
    "construction_other", "construction_stone", "construction_timber",
    "occupancy_tenant",
]

enriched_features = standard_features + [
    "flood_risk_zone", "crime_index", "distance_fire_station_km",
    "annual_rainfall_mm", "subsidence_risk",
]

target = "claim_severity"

train_df, test_df = train_test_split(claimants, test_size=0.3, random_state=42)
print(f"Train: {len(train_df):,} | Test: {len(test_df):,}")

# Save severity train/test splits to UC
spark.createDataFrame(train_df).write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_train_set")
spark.createDataFrame(test_df).write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_test_set")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Helper Functions

# COMMAND ----------

def gini_coefficient(y_true, y_pred):
    """Ordered Lorenz / Gini for model discrimination."""
    arr = np.array(sorted(zip(y_pred, y_true), key=lambda x: x[0]))
    cum_actual = np.cumsum(arr[:, 1])
    cum_actual_norm = cum_actual / cum_actual[-1]
    n = len(y_true)
    lorenz = cum_actual_norm.sum() / n
    return 2 * lorenz - 1


def evaluate_model(y_true, y_pred, model_name):
    """Compute severity-specific evaluation metrics."""
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    gini = gini_coefficient(y_true, y_pred)
    bias = (y_pred.mean() - y_true.mean()) / y_true.mean()

    return {
        "model": model_name,
        "mae": mae,
        "rmse": rmse,
        "mape": mape,
        "gini": gini,
        "mean_predicted": y_pred.mean(),
        "mean_actual": y_true.mean(),
        "bias_pct": bias * 100,
    }

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Train GBM — Model 1 (Standard Features)
# MAGIC
# MAGIC We use LightGBM with a **Gamma objective** — appropriate for severity because
# MAGIC claim costs are strictly positive and right-skewed.

# COMMAND ----------

lgb_params = {
    "objective": "gamma",
    "metric": "gamma_deviance",
    "learning_rate": 0.05,
    "num_leaves": 31,
    "min_child_samples": 50,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "verbose": -1,
    "seed": 42,
}

# --- Model 1: Standard ---
ds_train_std = lgb.Dataset(train_df[standard_features], label=train_df[target])
ds_val_std = lgb.Dataset(test_df[standard_features], label=test_df[target], reference=ds_train_std)

print("Training Model 1 (Standard features)...")
model_std = lgb.train(
    lgb_params,
    ds_train_std,
    num_boost_round=500,
    valid_sets=[ds_val_std],
    callbacks=[lgb.log_evaluation(100), lgb.early_stopping(50)],
)

pred_std = model_std.predict(test_df[standard_features])
metrics_std = evaluate_model(test_df[target].values, pred_std, "Standard")
print(f"  MAE: £{metrics_std['mae']:,.0f} | RMSE: £{metrics_std['rmse']:,.0f} | Gini: {metrics_std['gini']:.4f}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Train GBM — Model 2 (Enriched Features)

# COMMAND ----------

# --- Model 2: Enriched ---
ds_train_enr = lgb.Dataset(train_df[enriched_features], label=train_df[target])
ds_val_enr = lgb.Dataset(test_df[enriched_features], label=test_df[target], reference=ds_train_enr)

print("Training Model 2 (Enriched features)...")
model_enr = lgb.train(
    lgb_params,
    ds_train_enr,
    num_boost_round=500,
    valid_sets=[ds_val_enr],
    callbacks=[lgb.log_evaluation(100), lgb.early_stopping(50)],
)

pred_enr = model_enr.predict(test_df[enriched_features])
metrics_enr = evaluate_model(test_df[target].values, pred_enr, "Enriched")
print(f"  MAE: £{metrics_enr['mae']:,.0f} | RMSE: £{metrics_enr['rmse']:,.0f} | Gini: {metrics_enr['gini']:.4f}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Side-by-Side Metric Comparison

# COMMAND ----------

metric_names = ["MAE (£)", "RMSE (£)", "MAPE (%)", "Gini", "Mean Predicted (£)", "Mean Actual (£)", "Bias (%)"]
metric_keys = ["mae", "rmse", "mape", "gini", "mean_predicted", "mean_actual", "bias_pct"]

comparison = pd.DataFrame({
    "metric": metric_names,
    "model_1_standard": [f"{metrics_std[k]:.4f}" for k in metric_keys],
    "model_2_enriched": [f"{metrics_enr[k]:.4f}" for k in metric_keys],
})

spark_comp = spark.createDataFrame(comparison)
display(spark_comp)

spark_comp.write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_model_comparison")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 7. Feature Importance

# COMMAND ----------

def plot_feature_importance(model, features, title):
    importance = pd.DataFrame({
        "feature": features,
        "importance": model.feature_importance(importance_type="gain"),
    }).sort_values("importance", ascending=True)

    fig, ax = plt.subplots(figsize=(10, max(4, len(features) * 0.35)))
    ax.barh(importance["feature"], importance["importance"], color="#4C72B0")
    ax.set_xlabel("Importance (Gain)")
    ax.set_title(title)
    plt.tight_layout()
    plt.show()
    return importance

print("Model 1 — Standard Features:")
imp_std = plot_feature_importance(model_std, standard_features, "Feature Importance — Standard GBM")

print("\nModel 2 — Enriched Features:")
imp_enr = plot_feature_importance(model_enr, enriched_features, "Feature Importance — Enriched GBM")

# Save importance tables
imp_std["model"] = "standard"
imp_enr["model"] = "enriched"
imp_all = pd.concat([imp_std, imp_enr])
spark.createDataFrame(imp_all).write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_feature_importance")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 8. Lift Charts

# COMMAND ----------

def plot_lift_chart(y_true, y_pred, n_bins=10, label="Model"):
    df_lift = pd.DataFrame({"actual": y_true, "predicted": y_pred})
    df_lift["decile"] = pd.qcut(df_lift["predicted"], n_bins, labels=False, duplicates="drop")
    grouped = df_lift.groupby("decile").agg(
        avg_predicted=("predicted", "mean"),
        avg_actual=("actual", "mean"),
        count=("actual", "count"),
    ).reset_index()
    return grouped

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

for ax, pred, title in [
    (axes[0], pred_std, "Model 1 — Standard"),
    (axes[1], pred_enr, "Model 2 — Enriched"),
]:
    lift = plot_lift_chart(test_df[target].values, pred, label=title)
    ax.bar(lift["decile"] - 0.15, lift["avg_actual"], width=0.3, label="Actual", alpha=0.7, color="#2196F3")
    ax.bar(lift["decile"] + 0.15, lift["avg_predicted"], width=0.3, label="Predicted", alpha=0.7, color="#FF9800")
    ax.set_title(title)
    ax.set_xlabel("Severity Decile (low → high)")
    ax.set_ylabel("Average Claim Severity (£)")
    ax.legend()

plt.suptitle("Lift Chart — Predicted vs Actual Severity by Decile", fontsize=13)
plt.tight_layout()
plt.show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## 9. Severity Quotes & Loss Ratio Analysis
# MAGIC
# MAGIC We combine the frequency predictions from notebook 01 with our severity predictions
# MAGIC to produce **full burning-cost quotes**.

# COMMAND ----------

# Load the frequency-priced portfolio (test set from notebook 01)
priced = spark.table(f"{CATALOG}.{SCHEMA}.priced_portfolio").toPandas()

# Predict severity for ALL test policies (not just claimants)
sev_pred_std = model_std.predict(priced[standard_features])
sev_pred_enr = model_enr.predict(priced[enriched_features])

expense_load = 1.35

# Full quotes: frequency × severity × expense load
priced["sev_pred_standard"] = sev_pred_std
priced["sev_pred_enriched"] = sev_pred_enr
priced["full_quote_standard"] = np.round(priced["pred_freq_standard"] * sev_pred_std * expense_load, 2)
priced["full_quote_enriched"] = np.round(priced["pred_freq_enriched"] * sev_pred_enr * expense_load, 2)

# Save
spark.createDataFrame(priced).write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_priced_portfolio")

print(f"Avg full quote (standard): £{priced['full_quote_standard'].mean():.2f}")
print(f"Avg full quote (enriched): £{priced['full_quote_enriched'].mean():.2f}")
print(f"Avg actual loss:           £{priced['actual_loss'].mean():.2f}")

display(spark.table(f"{CATALOG}.{SCHEMA}.severity_priced_portfolio").select(
    "building_age", "bedrooms", "flood_risk_zone", "subsidence_risk",
    "full_quote_standard", "full_quote_enriched", "actual_loss"
).limit(20))

# COMMAND ----------

# Loss ratio by decile — using full quotes
lr_rows = []
for model_name, quote_col in [("Standard", "full_quote_standard"), ("Enriched", "full_quote_enriched")]:
    temp = priced.copy()
    temp["decile"] = pd.qcut(temp[quote_col], 10, labels=False, duplicates="drop")
    grouped = temp.groupby("decile").agg(
        total_premium=(quote_col, "sum"),
        total_loss=("actual_loss", "sum"),
        policy_count=("actual_loss", "count"),
    ).reset_index()
    grouped["loss_ratio"] = grouped["total_loss"] / grouped["total_premium"]
    grouped["model"] = model_name
    lr_rows.append(grouped)

lr_all = pd.concat(lr_rows)
spark.createDataFrame(lr_all).write.mode("overwrite").saveAsTable(f"{CATALOG}.{SCHEMA}.severity_loss_ratio_by_decile")

fig, ax = plt.subplots(figsize=(10, 5))
for model, color in [("Standard", "#E53935"), ("Enriched", "#43A047")]:
    subset = lr_all[lr_all["model"] == model]
    ax.plot(subset["decile"], subset["loss_ratio"], marker="o", label=model, color=color, linewidth=2)
ax.axhline(y=1.0, color="grey", linestyle="--", alpha=0.5, label="Breakeven (LR=1)")
ax.set_xlabel("Premium Decile (cheapest → most expensive)")
ax.set_ylabel("Loss Ratio")
ax.set_title("Loss Ratio by Full Quote Decile — Freq×Sev Standard vs Enriched")
ax.legend()
plt.tight_layout()
plt.show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## 10. Severity by Risk Segment

# COMMAND ----------

# Average severity prediction by flood risk zone
for col in ["flood_risk_zone", "subsidence_risk"]:
    seg = priced.groupby(col).agg(
        avg_sev_std=("sev_pred_standard", "mean"),
        avg_sev_enr=("sev_pred_enriched", "mean"),
        avg_actual_sev=("claim_severity", "mean"),
        n=("actual_loss", "count"),
    ).reset_index()
    seg["diff_pct"] = (seg["avg_sev_enr"] - seg["avg_sev_std"]) / seg["avg_sev_std"] * 100
    print(f"\n--- {col} ---")
    print(seg.to_string(index=False))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary of Persisted Artefacts
# MAGIC
# MAGIC | Artefact | Location |
# MAGIC |---|---|
# MAGIC | Severity train set | `.severity_train_set` |
# MAGIC | Severity test set | `.severity_test_set` |
# MAGIC | Severity model comparison | `.severity_model_comparison` |
# MAGIC | Feature importance | `.severity_feature_importance` |
# MAGIC | Full priced portfolio (freq×sev) | `.severity_priced_portfolio` |
# MAGIC | Loss ratios (full quotes) | `.severity_loss_ratio_by_decile` |
